name: Sync running data from running_page

on:
  workflow_dispatch:
  schedule:
    # utc time
    - cron: '0 18 * * *'
  

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  sync:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./syncer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Sync running_page
        run: |
          bash -c 'cd /home/user/bin/syncer && source /home/user/bin/syncer/venv/bin/activate && python running_page.py mikusugar/running_page'
